name: Install the executable binary
description: Install the executable binary from GitHub Releases

author: OKAMURA Naoki

inputs:
  hostname:
    description: "The GitHub hostname (useful for GitHub Enterprise) (default: github.com)"
    required: true
    default: "github.com"
  owner:
    description: "The GitHub repository owner name to install from"
    required: true
  repo:
    description: "The GitHub repository name"
    required: true
  version:
    description: "Version string for the installation binary"
    required: true
  archive:
    description: "Path to archive file"
    required: true
  sha256sum:
    description: "SHA-256 checksum for downloaded archive"
    required: true

  extract_command:
    description: "The command name for extracting files"
    required: true
    default: tar
  extract_flags:
    description: "The command-line flags fort the extraction command"
    required: true
    default: "-zxvf"
  install_file:
    description: "Installation filename"
    required: true
  install_path:
    description: "Installation path"
    required: true

runs:
  using: composite
  steps:
    - name: Install the executable binary from GitHub Releases
      shell: bash
      env:
        DOWNLOAD_URL: "https://${{ inputs.hostname }}/${{ inputs.owner }}/${{ inputs.repo }}/releases/download/${{ inputs.version }}/${{ inputs.archive }}"
        DOWNLOAD_SHA256SUM: "${{ inputs.sha256sum }}"

        EXTRACT_COMMAND: "${{ inputs.extract_command }}"
        EXTRACT_FLAGS: "${{ inputs.extract_flags }}"

        INSTALL_FILE: "${{ inputs.install_file }}"
        INSTALL_PATH: "${{ inputs.install_path }}"
      run: |
        set -xeuo pipefail

        declare cwd
        cwd="$(pwd)"

        declare tmp
        tmp="$(mktemp -d)"
        cd "${tmp}"

        cat <<... > sha256sum.txt
        ${DOWNLOAD_SHA256SUM} payload.data
        ...

        curl -L -o payload.data "${DOWNLOAD_URL}"
        sha256sum --check sha256sum.txt

        "${EXTRACT_COMMAND}" "${EXTRACT_FLAGS}" payload.data
        install -Dm755 "${INSTALL_FILE}" "${cwd}/${INSTALL_PATH}"

        cd "${cwd}"
        rm "${tmp}" -rd
